### PR TITLE
Frmbuf cleanup

### PR DESCRIPTION
**Pull request by radheyxilinx**
Hi,

This PR has pending cleanup patches from 4.6_vcu_proto branch.
(https://gitenterprise.xilinx.com/PAEG/linux-xlnx/tree/2016.3/4.6_vcu_proto)
This PR is based on jnichols62:video_branch.

Thanks,
Radhey

### CODE REVIEW

**Comment by chkohn** [comment]
@jnichols62 can you ack these two patches and test on your end?
@radheyxilinx have you tested this entire series and everything is working for you?

**Comment by radheyxilinx** [comment]
Hi  Chris,

I am currently validating HDMI-RX with framebuffer write.  
But pipeline is still not validated since i see no-link error. 
bash> media-ctl -p    
<snip> 
           [fmt:unknown/1280x720]
                [dv.caps:BT.656/1120 min:0x0@25000000 max:4096x2160@297000000 stds:CEA-861,DMT,CVT,GTF caps:progressive,reduced-blanking,custom]
                [dv.query:no-link]

I will reply to this PR once i test the pipeline.
I think PR can be merged once we get an ACK from John.

-Radhey

**Comment by chkohn** [comment]
You should reach out to Rohit C about HDMI Rx validation. It looks like the EDID might not be programmed correctly. I haven't tested this in a while and I know there are several options for EDID programming and some might be disabled temporarily.

**Comment by radheyxilinx** [comment]
Thanks Chris. I have dropped an email to Rohit C.
@jnichols62 : Have you tested this PR? including framebuffer cleanup patches.

**Comment by radheyxilinx** [comment]
@jnichols62 : Please send out patch for Xilinx V4L2 bridge driver which sets xilinx_xdma_config in dma channel private data else dma_prep_interleaved will fail.

<snip> kernel dump 
xilinx-frmbuf a0030000.fb_wr: Missing dma config in dma_chan obj

**Pull request closed without merging**
